# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(first_name:"Derek", last_name:"Yang", email:"dyy2105@columbia.edu", password:"1234")
User.create(first_name:"Jesusmar", last_name:"lima", email:"jesusmarlima@gmail.com",password:"1234")
User.create(first_name:"Olivia", last_name:"coffaro", email:"ofcoffaro@gmail.com",password:"1234")

Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Drive Across the Golden Gate Bridge')
Activity.create(op: 0.2, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Grand Canyon')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to a music festival')
Activity.create(op: 0.4, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Ireland for S Patricks Day')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to Octoberfest')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Boot of Beer')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Attend the Superbowl')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'The Northern Lights')
Activity.create(op: 0.7, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Get married')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Have a child')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Learn how to play tennis')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Write a screenplay')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Write a book or short story or poem')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Watch the sun rise')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go on a blind date')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Learn to knit')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Dream journal')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Try being a vegetarian')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Try being a vegan')
Activity.create(op: 0.7, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Run a 5k')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Water skiing')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Snow skiing')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Mardi gras in new Orleans')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Fire walk')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Niagara falls')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Get too drunk and live to tell the tale')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'The places where the four states meet')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go inside the white house')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to paris with a lover')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Road Trip')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'streaking')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Road trip in an RV')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Eat at one of the worlds top ten restaurants')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Solve a rubiks cube')
Activity.create(op: 0.4, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Do something scary')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to the Olympics (to watch)')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Practice a new language')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'See the giant trees in California')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Milk a cow')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Michau piccau')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Meditation retreat')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Ride a segway')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Polar bear club')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Ride a motorcycle')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Get a tattoo')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Try weird fried stuff at a state fair')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Paint')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to Disney world')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Take a cooking class')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go skinny dipping')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Own a rolex')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'See a broadway show')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Be in love')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Graduate Highschool')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Graduate college')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Start media scandal')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to a renascence fair')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Balloon ride')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Parasailing')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Learn to sew')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Shoot skeet')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Prada marfa')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Learn to skateboard')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Start your own business')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Cherry blossoms')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Run with the bulls in spain')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Skydiving')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Bungie Jumping')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'roller coaster')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'snorkeling')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'scuba diving')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'speak another language')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'volunteer your time')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'do something ccrazy to your hair')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'vote')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'spend the whole day in bed')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'get your dream job')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'see an opera')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'see a ballet')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'leaned how to dance')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'eat dumplings in china town')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'crashed a party')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'crash a wedding')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'set a guiness world record')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'win a contest')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'be on TV')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'15 mins of fame')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'hot air balloon ride')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'gamble')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'has sex on a beach')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'dance in the rain')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'swim with dolphins')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'take a photo in a photo booth')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Drive in movie')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'ride a camel')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'ride a horse')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'visit niagra falls')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'heli-ski')
Activity.create(op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'ride in a heliopter')



# ListItem.create(user_id: 1, activity_id: 1)
# ListItem.create(user_id: 1, activity_id: 6)
# ListItem.create(user_id: 1, activity_id: 10)
# ListItem.create(user_id: 1, activity_id: 15)
# ListItem.create(user_id: 1, activity_id: 70)
# ListItem.create(user_id: 1, activity_id: 56)
# ListItem.create(user_id: 1, activity_id: 14)
# ListItem.create(user_id: 1, activity_id: 67)
# ListItem.create(user_id: 1, activity_id: 2)
# ListItem.create(user_id: 1, activity_id: 90)
#
# ListItem.create(user_id: 2, activity_id: 3)
# ListItem.create(user_id: 2, activity_id: 2)
# ListItem.create(user_id: 2, activity_id: 37)
# ListItem.create(user_id: 2, activity_id: 35)
# ListItem.create(user_id: 2, activity_id: 31)
# ListItem.create(user_id: 2, activity_id: 36)
# ListItem.create(user_id: 2, activity_id: 34)
# ListItem.create(user_id: 2, activity_id: 37)
# ListItem.create(user_id: 2, activity_id: 9)
# ListItem.create(user_id: 2, activity_id: 30)
#
# ListItem.create(user_id: 3, activity_id: 5)
# ListItem.create(user_id: 3, activity_id: 4)
# ListItem.create(user_id: 3, activity_id: 40)
# ListItem.create(user_id: 3, activity_id: 45)
# ListItem.create(user_id: 3, activity_id: 41)
# ListItem.create(user_id: 3, activity_id: 46)
# ListItem.create(user_id: 3, activity_id: 44)
# ListItem.create(user_id: 3, activity_id: 47)
# ListItem.create(user_id: 3, activity_id: 6)
# ListItem.create(user_id: 3, activity_id: 48)
