# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(first_name:"Derek", last_name:"Yang", email:"dyy2105@columbia.edu", password:"1234")
User.create(first_name:"Jesusmar", last_name:"lima", email:"jesusmarlima@gmail.com",password:"1234")
User.create(first_name:"Olivia", last_name:"coffaro", email:"ofcoffaro@gmail.com",password:"1234")

Activity.create(photo_id: 605792, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Drive Across the Golden Gate Bridge')
Activity.create(photo_id: 463393, op: 0.2, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Grand Canyon')
Activity.create(photo_id: 55554, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to a music festival')
Activity.create(photo_id: 533144, op: 0.4, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:"Travel to Ireland for St. Patrick's Day")
Activity.create(photo_id: 12291, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to Octoberfest')
Activity.create(photo_id: 369770, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Drink a boot of Beer')
Activity.create(photo_id: 686533, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Attend the Superbowl')
Activity.create(photo_id: 492565, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'See the Northern Lights')
Activity.create(photo_id: 639559, op: 0.7, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Get married')
Activity.create(photo_id: 47, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Have a child')
Activity.create(photo_id: 503, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Learn how to play tennis')
Activity.create(photo_id: 114865, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Write a screenplay')
Activity.create(photo_id: 114865, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Write a book')
Activity.create(photo_id: 114865, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Write a short story')
Activity.create(photo_id: 114865, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Write a poem')
Activity.create(photo_id: 707015, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Watch the sun rise')
Activity.create(photo_id: 94836, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go on a blind date')
Activity.create(photo_id: 205693, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Learn to knit')
Activity.create(photo_id: 1216, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Keep a dream journal')
Activity.create(photo_id: 674572, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Try being a vegetarian')
Activity.create(photo_id: 674572, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Try being a vegan')
Activity.create(photo_id: 685051, op: 0.7, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Run a 5k')
Activity.create(photo_id: 15538, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Water skiing')
Activity.create(photo_id: 178034, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Skiing')
Activity.create(photo_id: 61398, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Mardi gras in new Orleans')
Activity.create(photo_id: 551771, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Fire walk')
Activity.create(photo_id: 380406, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Niagara falls')
Activity.create(photo_id: 662544, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Get too drunk and live to tell the tale')
Activity.create(photo_id: 68014, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Visit the White House')
Activity.create(photo_id: 588692, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to Paris with a lover')
Activity.create(photo_id: 48569, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Road Trip')
Activity.create(photo_id: 107229, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Streaking')
Activity.create(photo_id: 707894 , op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Road trip in an RV')
Activity.create(photo_id: 18791, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Solve a rubiks cube')
Activity.create(photo_id: 668474, op: 0.4, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Do something scary')
Activity.create(photo_id: 550542, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to the Olympics')
Activity.create(photo_id: 532871, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Practice a new language')
Activity.create(photo_id: 563817, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'See the giant trees in California')
Activity.create(photo_id: 562381, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Milk a cow')
Activity.create(photo_id: 543941, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Machu Picchu')
Activity.create(photo_id: 584447, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Meditate')
Activity.create(photo_id: 12010, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Ride a segway')
Activity.create(photo_id: 489267, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Join the polar bear club')
Activity.create(photo_id: 4911, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Ride a motorcycle')
Activity.create(photo_id: 551700, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Get a tattoo')
Activity.create(photo_id: 535367, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Paint')
Activity.create(photo_id: 262417, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to Disney World')
Activity.create(photo_id: 518277, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Take a cooking class')
Activity.create(photo_id: 8130, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go skinny dipping')
Activity.create(photo_id: 656103, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Own a rolex')
Activity.create(photo_id: 105324, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'See a show on Broadway')
Activity.create(photo_id: 610235, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Be in love')
Activity.create(photo_id: 66573, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Graduate Highschool')
Activity.create(photo_id: 66573, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Graduate college')
Activity.create(photo_id: 683064, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Start media scandal')
Activity.create(photo_id: 647055, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go to a renaissance fair')
Activity.create(photo_id: 34461, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Parasailing')
Activity.create(photo_id: 102512, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Learn to sew')
Activity.create(photo_id: 693923, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Shoot clay pigeons')
Activity.create(photo_id: 174172, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Prada Marfa')
Activity.create(photo_id: 639531, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Learn to skateboard')
Activity.create(photo_id: 101419, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Start a business')
Activity.create(photo_id: 425175, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Cherry blossoms')
Activity.create(photo_id: 562715, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Run with the bulls in Spain')
Activity.create(photo_id: 28233, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Skydiving')
Activity.create(photo_id: 114402, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Bungie Jumping')
Activity.create(photo_id: 625356, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Ride a Roller Coaster')
Activity.create(photo_id: 607775, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go Snorkeling')
Activity.create(photo_id: 242, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Go Scuba Diving')
Activity.create(photo_id: 24074, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Speak another language')
Activity.create(photo_id: 689837, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Volunteer')
Activity.create(photo_id: 38415, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Get a crazy haircut')
Activity.create(photo_id: 542915, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Vote')
Activity.create(photo_id: 19163, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Spend the whole day in bed')
Activity.create(photo_id: 702386, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Land a dream job')
Activity.create(photo_id: 695164, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'See an Opera')
Activity.create(photo_id: 92568, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'See a ballet')
Activity.create(photo_id: 682585, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Dance')
Activity.create(photo_id: 573888, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Eat dumplings in Chinatown')
Activity.create(photo_id: 76283, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Crash a party')
Activity.create(photo_id: 76283, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Crash a wedding')
Activity.create(photo_id: 42908, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Set a World Record')
Activity.create(photo_id: 319206, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Win a contest')
Activity.create(photo_id: 705913, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Be on TV')
Activity.create(photo_id: 561751, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'15 mins of fame')
Activity.create(photo_id: 599669, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Hot air balloon ride')
Activity.create(photo_id: 369911, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Gamble')
Activity.create(photo_id: 537717, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title: 'Sex on a beach')
Activity.create(photo_id: 703219, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Swim with dolphins')
Activity.create(photo_id: 31745, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Photo booth')
Activity.create(photo_id: 55133, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Drive in movie')
Activity.create(photo_id: 492689, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Ride a camel')
Activity.create(photo_id: 583093, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Ride a horse')
Activity.create(photo_id: 683759, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Heli-ski')
Activity.create(photo_id: 564174, op: 0.1, co: 0.5, ex: 0.9, ag: 0.4, ne: 0.8,  title:'Helicopter Ride')




# ListItem.create(user_id: 1, activity_id: 1)
# ListItem.create(user_id: 1, activity_id: 6)
# ListItem.create(user_id: 1, activity_id: 10)
# ListItem.create(user_id: 1, activity_id: 15)
# ListItem.create(user_id: 1, activity_id: 70)
# ListItem.create(user_id: 1, activity_id: 56)
# ListItem.create(user_id: 1, activity_id: 14)
# ListItem.create(user_id: 1, activity_id: 67)
# ListItem.create(user_id: 1, activity_id: 2)
# ListItem.create(user_id: 1, activity_id: 90)
#
# ListItem.create(user_id: 2, activity_id: 3)
# ListItem.create(user_id: 2, activity_id: 2)
# ListItem.create(user_id: 2, activity_id: 37)
# ListItem.create(user_id: 2, activity_id: 35)
# ListItem.create(user_id: 2, activity_id: 31)
# ListItem.create(user_id: 2, activity_id: 36)
# ListItem.create(user_id: 2, activity_id: 34)
# ListItem.create(user_id: 2, activity_id: 37)
# ListItem.create(user_id: 2, activity_id: 9)
# ListItem.create(user_id: 2, activity_id: 30)
#
# ListItem.create(user_id: 3, activity_id: 5)
# ListItem.create(user_id: 3, activity_id: 4)
# ListItem.create(user_id: 3, activity_id: 40)
# ListItem.create(user_id: 3, activity_id: 45)
# ListItem.create(user_id: 3, activity_id: 41)
# ListItem.create(user_id: 3, activity_id: 46)
# ListItem.create(user_id: 3, activity_id: 44)
# ListItem.create(user_id: 3, activity_id: 47)
# ListItem.create(user_id: 3, activity_id: 6)
# ListItem.create(user_id: 3, activity_id: 48)

Type.create(photo_id: 7285, title: "INTJ", nickname: "THE ARCHITECT", content: "It’s lonely at the top, and being one of the rarest and most strategically capable personality types, INTJs know this all too well. INTJs form just two percent of the population, and women of this personality type are especially rare, forming just 0.8% of the population – it is often a challenge for them to find like-minded individuals who are able to keep up with their relentless intellectualism and chess-like maneuvering. People with the INTJ personality type are imaginative yet decisive, ambitious yet private, amazingly curious, but they do not squander their energy.")
Type.create(photo_id: 545816, title: "INTP", nickname: "THE LOGICIAN", content: "The INTP personality type is fairly rare, making up only three percent of the population, which is definitely a good thing for them, as there's nothing they'd be more unhappy about than being 'common'. INTPs pride themselves on their inventiveness and creativity, their unique perspective and vigorous intellect. Usually known as the philosopher, the architect, or the dreamy professor, INTPs have been responsible for many scientific discoveries throughout history.")
Type.create(photo_id: 7285,title: "ENTJ", nickname: "THE COMMANDER", content: "ENTJs are natural-born leaders. People with this personality type embody the gifts of charisma and confidence, and project authority in a way that draws crowds together behind a common goal. But unlike their Feeling (F) counterpart, ENTJs are characterized by an often ruthless level of rationality, using their drive, determination and sharp minds to achieve whatever end they've set for themselves. Perhaps it is best that they make up only three percent of the population, lest they overwhelm the more timid and sensitive personality types that make up much of the rest of the world – but we have ENTJs to thank for many of the businesses and institutions we take for granted every day.")
Type.create(photo_id: 28286, title: "ENTP", nickname: "THE DEBATER", content: "The ENTP personality type is the ultimate devil's advocate, thriving on the process of shredding arguments and beliefs and letting the ribbons drift in the wind for all to see. Unlike their more determined Judging (J) counterparts, ENTPs don't do this because they are trying to achieve some deeper purpose or strategic goal, but for the simple reason that it's fun. No one loves the process of mental sparring more than ENTPs, as it gives them a chance to exercise their effortlessly quick wit, broad accumulated knowledge base, and capacity for connecting disparate ideas to prove their points.")
Type.create(photo_id: 7285, title: "INFJ", nickname: "THE ADVOCATE", content: "The INFJ personality type is very rare, making up less than one percent of the population, but they nonetheless leave their mark on the world. As Diplomats (NF), they have an inborn sense of idealism and morality, but what sets them apart is the accompanying Judging (J) trait – INFJs are not idle dreamers, but people capable of taking concrete steps to realize their goals and make a lasting positive impact.")
Type.create(photo_id: 690079, title: "INFP", nickname: "THE MEDIATOR", content: "INFP personalities are true idealists, always looking for the hint of good in even the worst of people and events, searching for ways to make things better. While they may be perceived as calm, reserved, or even shy, INFPs have an inner flame and passion that can truly shine. Comprising just 4% of the population, the risk of feeling misunderstood is unfortunately high for the INFP personality type – but when they find like-minded people to spend their time with, the harmony they feel will be a fountain of joy and inspiration.")
Type.create(photo_id: 1548, title: "ENFJ", nickname: "THE PROTAGONIST", content: "ENFJs are natural-born leaders, full of passion and charisma. Forming around two percent of the population, they are oftentimes our politicians, our coaches and our teachers, reaching out and inspiring others to achieve and to do good in the world. With a natural confidence that begets influence, ENFJs take a great deal of pride and joy in guiding others to work together to improve themselves and their community.")
Type.create(photo_id: 28286, title: "ENFP", nickname: "THE CAMPAIGNER", content: "The ENFP personality is a true free spirit. They are often the life of the party, but unlike Explorers, they are less interested in the sheer excitement and pleasure of the moment than they are in enjoying the social and emotional connections they make with others. Charming, independent, energetic and compassionate, the 7% of the population that they comprise can certainly be felt in any crowd.")
Type.create(photo_id: 7285, title: "ISTJ", nickname: "THE LOGISTICIAN", content: "The ISTJ personality type is thought to be the most abundant, making up around 13% of the population. Their defining characteristics of integrity, practical logic and tireless dedication to duty make ISTJs a vital core to many families, as well as organizations that uphold traditions, rules and standards, such as law offices, regulatory bodies and military. People with the ISTJ personality type enjoy taking responsibility for their actions, and take pride in the work they do – when working towards a goal, ISTJs hold back none of their time and energy completing each relevant task with accuracy and patience.")
Type.create(photo_id: 7285, title: "ISFJ", nickname: "THE DEFENDER", content: "The ISFJ personality type is quite unique, as many of their qualities defy the definition of their individual traits. Though possessing the Feeling (F) trait, ISFJs have excellent analytical abilities; though Introverted (I), they have well-developed people skills and robust social relationships; and though they are a Judging (J) type, ISFJs are often receptive to change and new ideas. As with so many things, people with the ISFJ personality type are more than the sum of their parts, and it is the way they use these strengths that defines who they are.")
Type.create(photo_id: 7285, title: "ESTJ", nickname: "THE EXECUTIVE", content: "ESTJs are representatives of tradition and order, utilizing their understanding of what is right, wrong and socially acceptable to bring families and communities together. Embracing the values of honesty, dedication and dignity, people with the ESTJ personality type are valued for their clear advice and guidance, and they happily lead the way on difficult paths. Taking pride in bringing people together, ESTJs often take on roles as community organizers, working hard to bring everyone together in celebration of cherished local events, or in defense of the traditional values that hold families and communities together.")
Type.create(photo_id: 7285, title: "ESFJ", nickname: "THE CONSUL", content: "People who share the ESFJ personality type are, for lack of a better word, popular – which makes sense, given that it is also a very common personality type, making up twelve percent of the population. In high school, ESFJs are the cheerleaders and the quarterbacks, setting the tone, taking the spotlight and leading their teams forward to victory and fame. Later in life, ESFJs continue to enjoy supporting their friends and loved ones, organizing social gatherings and doing their best to make sure everyone is happy.")
Type.create(photo_id: 7285, title: "ISTP", nickname: "THE VIRTUOSO", content: "ISTPs love to explore with their hands and their eyes, touching and examining the world around them with cool rationalism and spirited curiosity. People with this personality type are natural Makers, moving from project to project, building the useful and the superfluous for the fun of it, and learning from their environment as they go. Often mechanics and engineers, ISTPs find no greater joy than in getting their hands dirty pulling things apart and putting them back together, just a little bit better than they were before.")
Type.create(photo_id: 637852, title: "ISFP", nickname: "THE ADVENTURER", content: "ISFP personality types are true artists, but not necessarily in the typical sense where they're out painting happy little trees. Often enough though, they are perfectly capable of this. Rather, it's that they use aesthetics, design and even their choices and actions to push the limits of social convention. ISFPs enjoy upsetting traditional expectations with experiments in beauty and behavior – chances are, they've expressed more than once the phrase 'Don't box me in!'")
Type.create(photo_id: 7285, title: "ESTP", nickname: "THE ENTREPRENEUR", content: "ESTP personality types always have an impact on their immediate surroundings – the best way to spot them at a party is to look for the whirling eddy of people flitting about them as they move from group to group. Laughing and entertaining with a blunt and earthy humor, ESTP personalities love to be the center of attention. If an audience member is asked to come on stage, ESTPs volunteer – or volunteer a shy friend.")
Type.create(photo_id: 1548, title: "ESNP", nickname: "THE ENTERTAINER", content: "If anyone is to be found spontaneously breaking into song and dance, it is the ESFP personality type. ESFPs get caught up in the excitement of the moment, and want everyone else to feel that way, too. No other personality type is as generous with their time and energy as ESFPs when it comes to encouraging others, and no other personality type does it with such irresistible style.")
